language: ruby

rvm:
    - 2.2
    
cache:
  directories:
    - cache

before_install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update

install:
    - wget https://github.com/jgm/pandoc/releases/download/1.17.1/pandoc-1.17.1-2-amd64.deb
    - sudo dpkg -i pandoc-1.17.1-2-amd64.deb
    - sudo apt-get install ttf-wqy-microhei texlive-xetex texlive-latex-extra

script:
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "$GIT_NAME"
    - git clone --depth 1 https://$GIT_TOKEN@github.com/Bekcpear/bekcpear.github.io git
    - pwd
    - ls -a
    - make all
    - cd git
    - ls -a
    - git add -A .
    - git commit -m "update from travis" 
    - git push --quiet
    
after_success:
    - echo "Welcome to my home page: https://bekcpear.io"
